services:
  - type: web
    name: recommendation-based-telemedicine
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://localhost:3306/recommendation-based_telemedicine  # Add your database URL if needed
      - key: SPRING_DATASOURCE_USERNAME
        value: root
      - key: SPRING_DATASOURCE_PASSWORD
        value: ""
      - key: SERVER_PORT
        value: 8080
    runtime: docker
